---

is_debug: true
listen:
  type: port
  bind_ip: localhost
  port: 10000
storage:
  host: 127.0.0.1
  port: 5432
  database: Services
  username: postgres
  password: AlexPAV2307
  max_attempts: 3
